//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analytics
{
   // using Microsoft.Data.Entity;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    //using System.Data.Entity.Infrastructure;
    
    public partial class shortenurlEntities : DbContext
    {
        public shortenurlEntities() : base("name=shortenurlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<batchuploaddata> batchuploaddatas { get; set; }
        public DbSet<city_blocks_ipv4_geolite2> city_blocks_ipv4_geolite2 { get; set; }
        public DbSet<client> clients { get; set; }
        public DbSet<cookietable> cookietables { get; set; }
        public DbSet<countrydata> countrydatas { get; set; }
        public DbSet<countrydata_ipv4_geolite2> countrydata_ipv4_geolite2 { get; set; }
        public DbSet<errorlog> errorlogs { get; set; }
        public DbSet<freegeoipdata> freegeoipdatas { get; set; }
        public DbSet<hashidlist> hashidlists { get; set; }
        public DbSet<locations_data> locations_data { get; set; }
        public DbSet<loginhistory> loginhistories { get; set; }
        public DbSet<master_location> master_location { get; set; }
        public DbSet<riddata> riddatas { get; set; }
        public DbSet<shorturldata> shorturldatas { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<tmp_rownum_update> tmp_rownum_update { get; set; }
        public DbSet<uiddata> uiddatas { get; set; }
        public DbSet<city_locations_geolite2> city_locations_geolite2 { get; set; }
        public DbSet<countrydata_geolite2> countrydata_geolite2 { get; set; }
    }
}
